/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is checked in here so
// TypeScript works immediately after cloning the MVP.
